#!/usr/bin/env node

import { randomBytes } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const DEFAULT_CONFIG = '/etc/tar1090/tokens.json';

function getConfigPath() {
  const idx = process.argv.indexOf('--config');
  return idx !== -1 && process.argv[idx + 1] ? process.argv[idx + 1] : DEFAULT_CONFIG;
}

function readConfig(path) {
  if (!existsSync(path)) return { sitePassword: null, tokens: {} };
  return JSON.parse(readFileSync(path, 'utf-8'));
}

function writeConfig(config, path) {
  const dir = dirname(path);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  writeFileSync(path, JSON.stringify(config, null, 2) + '\n');
  writeMapFile(config, path.replace(/\.json$/, '.map'));
  console.log(`\n⚠  Run 'nginx -s reload' to apply changes`);
}

function writeMapFile(config, mapPath) {
  const lines = ['# Generated by scripts/token.mjs — do not edit manually'];
  if (config.sitePassword) lines.push(`"${config.sitePassword}" 1;`);
  for (const token of Object.keys(config.tokens)) lines.push(`"${token}" 1;`);
  writeFileSync(mapPath, lines.join('\n') + '\n');
}

function generateToken() {
  return 'tk_' + randomBytes(16).toString('hex');
}

function parseExpires(str) {
  const m = str.match(/^(\d+)(d|h|m)$/);
  if (!m) {
    console.error(`Invalid expires format: ${str} (use e.g. 7d, 24h, 30m)`);
    process.exit(1);
  }
  const n = parseInt(m[1], 10);
  const unit = { d: 86400, h: 3600, m: 60 }[m[2]];
  return Math.floor(Date.now() / 1000) + n * unit;
}

function getArg(name) {
  const idx = process.argv.indexOf(name);
  return idx !== -1 && process.argv[idx + 1] ? process.argv[idx + 1] : null;
}

function printUsage() {
  console.log('Usage: token.mjs <command>');
  console.log('');
  console.log('Commands:');
  console.log('  set-password <password>               Set the site password');
  console.log('  create --expires <duration> [--note]  Create a share token');
  console.log('  revoke <token>                        Revoke a share token');
  console.log('  list                                  List all tokens');
  console.log('  gc                                    Remove expired tokens');
  console.log('');
  console.log('Options:');
  console.log('  --config <path>  Config file path (default: /etc/tar1090/tokens.json)');
  console.log('  --help           Show this help message');
}

// ── Commands ──

const [, , command, ...rest] = process.argv;

if (command === '--help' || command === '-h' || command === 'help' || command === undefined) {
  printUsage();
  process.exit(0);
}

const configPath = getConfigPath();
const config = readConfig(configPath);

switch (command) {
  case 'set-password': {
    const pw = rest.find((a) => !a.startsWith('-'));
    if (!pw) {
      console.error('Usage: token.mjs set-password <password>');
      process.exit(1);
    }
    config.sitePassword = pw;
    writeConfig(config, configPath);
    console.log('Site password updated.');
    break;
  }

  case 'create': {
    const expiresStr = getArg('--expires');
    const note = getArg('--note') ?? '';
    if (!expiresStr) {
      console.error('Usage: token.mjs create --expires 7d [--note "..."]');
      process.exit(1);
    }
    const token = generateToken();
    const expires = parseExpires(expiresStr);
    config.tokens[token] = {
      created: Math.floor(Date.now() / 1000),
      expires,
      note,
    };
    writeConfig(config, configPath);
    const expDate = new Date(expires * 1000).toISOString().slice(0, 10);
    console.log(`Created token ${token} (expires ${expDate})`);
    console.log(`Share URL: https://your-site.com/login.html?token=${token}`);
    break;
  }

  case 'revoke': {
    const tokenId = rest.find((a) => !a.startsWith('-'));
    if (!tokenId) {
      console.error('Usage: token.mjs revoke <token>');
      process.exit(1);
    }
    if (!(tokenId in config.tokens)) {
      console.error(`Token not found: ${tokenId}`);
      process.exit(1);
    }
    delete config.tokens[tokenId];
    writeConfig(config, configPath);
    console.log(`Revoked token ${tokenId}`);
    break;
  }

  case 'list': {
    const now = Math.floor(Date.now() / 1000);
    console.log('Site password:', config.sitePassword ? '(set)' : '(not set)');
    console.log('');
    const entries = Object.entries(config.tokens);
    if (entries.length === 0) {
      console.log('No share tokens.');
      break;
    }
    for (const [token, meta] of entries) {
      const exp = meta.expires;
      const expired = exp > 0 && exp < now;
      const expStr = exp === 0 ? 'never' : new Date(exp * 1000).toISOString().slice(0, 10);
      console.log(`${token}  expires=${expStr}${expired ? ' [EXPIRED]' : ''}  note="${meta.note}"`);
    }
    break;
  }

  case 'gc': {
    const now = Math.floor(Date.now() / 1000);
    let removed = 0;
    for (const [token, meta] of Object.entries(config.tokens)) {
      if (meta.expires > 0 && meta.expires < now) {
        delete config.tokens[token];
        removed++;
      }
    }
    if (removed > 0) {
      writeConfig(config, configPath);
      console.log(`Removed ${removed} expired token(s).`);
    } else {
      console.log('No expired tokens to clean.');
    }
    break;
  }

  default:
    printUsage();
    process.exit(1);
}
